# Generated by Django 2.0.2 on 2018-04-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='node',
            table='nodes',
        ),
    ]
