# Generated by Django 2.0.2 on 2018-04-29 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_auto_20180428_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DensityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_records', to='lights.Node')),
            ],
            options={
                'db_table': 'densityrecords',
            },
        ),
    ]
